### PR TITLE
CSV Output

### PR DESCRIPTION
**Pull request by nickschuch**
The following allows for easy scripting edge cases.

For example, If I wanted to write a little script to output the errors for a site:

```
$ dashboard-console snapshots --csv --client-id=telco | cut -d ',' -f 5
1
2
```

This output only occurs when the `--csv` flag is selected.

### CODE REVIEW

**Comment by kimpepper** [comment]
Needs tests.

**Comment by nickschuch** [comment]
Good call, are you happy with the feature?

**Comment by nickschuch** [comment]
I know have bitbar scripts giving me:

screen shot 2016-01-12 at 10 54 13 am

**Comment by kimpepper** [comment]
You can always just call the web service directly, and parse the json response?

**Comment by nickschuch** [comment]
I could, but then I would still need to handle the json with something and then bash it up a bit. So thought this might be a nice abstraction for others to use as well.

**Comment by nickschuch** [comment]
Output of the `--csv`

```
telco,telconsw_dev,20,30,1
telco,telconsw_test,20,30,2
thansw,thansw_dev,52,14,2
thansw,thansw_prod,52,14,2
thansw,thansw_test,52,14,2
wfl,wfl_qa,44,45,4
wiro,wiro_prod,83,34,0
wiro,wiro_qa,83,34,0
wiro,wiro_staging,83,34,0
```

**Comment by kimpepper** [comment]
CSV is a lot more brittle. If we add another column or change the order, stuff that depends on that will need to be changed. Using json, we just pull out the values we need.

**Comment by nickschuch** [comment]
It doesn't have to be CSV, but I am looking for an output which is easy to `cut` via bash for scripting.

If I have to write my own little CLI to get this done then Im ok with that, but I didn't want to duplicate work.

**Comment by kimpepper** [comment]
OK then. Seems a waste to create a new client just for that.

**Comment by nickschuch** [comment]
Thanks mate, Ill get the test coverage going and update when ready.

**Pull request merged**
